apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
  name: {{ .Chart.Name }}
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/{{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      name: {{ .Chart.Name }}
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.service.nodePool }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
          - name: BASE_STORAGE_URL
            valueFrom:
              configMapKeyRef:
                key: baseStorageUrl
                name: {{ .Chart.Name }}
          - name: BASE_STREAM_URL
            valueFrom:
              configMapKeyRef:
                key: baseStreamUrl
                name: {{ .Chart.Name }}
          - name: SMCA
            valueFrom:
              configMapKeyRef:
                key: smca
                name: {{ .Chart.Name }}
          - name: VERIFIER_URL
            valueFrom:
              configMapKeyRef:
                key: verifierRpcAddr
                name: {{ .Chart.Name }}
          - name: VERIFIER_RPC_ADDR
            valueFrom:
              configMapKeyRef:
                key: verifierRpcAddr
                name: {{ .Chart.Name }}
          - name: BUCKET
            valueFrom:
              configMapKeyRef:
                key: bucket
                name: {{ .Chart.Name }}
          - name: NATS_URL
            valueFrom:
              configMapKeyRef:
                key: natsUrl
                name: {{ .Chart.Name }}
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                key: clusterId
                name: {{ .Chart.Name }}
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                key: logLevel
                name: {{ .Chart.Name }}
          - name: BLOCKCHAIN_URL
            valueFrom:
              secretKeyRef:
                key: blockchainUrl
                name: {{ .Chart.Name }}
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Chart.Name }}
                key: password
          - name: HASH_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Chart.Name }}
                key: hash
          - name: NATS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Chart.Name }}
                key: token
          - name: VERIFIER_RPC_ADDR
            value: verifier:50055
          - name: OUTPUT_DIR
            value: /opt/mnt/
          - name: MANAGER_RPC_ADDR
            value: manager:50051
          - name: KEY_FILE
            value: keys/transcoder.key
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          requests: {}
