setup_remote_docker: &setup_remote_docker
  version: 18.06.0-ce
  reusable: true
  exclusive: true
  docker_layer_caching: true

docker_login: &docker_login
  name: docker login
  command: |
    docker login -u _json_key -p "$GCLOUD_SERVICE_KEY" https://gcr.io

run_consul: &run_consul
  name: run consul proxy
  command: |
    kubectl port-forward config-consul-0 8500
  background: true

init_gcloud: &init_gcloud
  name: Init gcloud
  command: .circleci/init-gcloud.sh

base_docker_image: &base_docker_image
  - image: gcr.io/videocoin-network/cloud-base-ci:1.0
    auth:
      username: _json_key
      password: $GCLOUD_SERVICE_KEY

restore_repo: &restore_repo
  restore_cache:
    keys:
      - v1-repo-{{ .Branch }}-{{ .Revision }}
      - v1-repo-{{ .Branch }}
      - v1-repo

defaults: &defaults
  working_directory: /go/src/github.com/videocoin/transcode
  docker: *base_docker_image

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - setup_remote_docker:
          <<: *setup_remote_docker
      - run:
          <<: *docker_login
      - run:
          name: lint
          command: |
            make docker-lint
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  build:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - setup_remote_docker:
          <<: *setup_remote_docker
      - run:
          <<: *docker_login
      - run:
          name: release
          command: |
            make release
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          <<: *setup_remote_docker
      - run:
          <<: *init_gcloud
      - run:
          <<: *run_consul
      - run:
          name: deploy binary
          command: |
            timeout -t 15 bash .circleci/wait-consul.sh
            make deploy
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - sandbox
      #           - develop
      #           - staging
